In [1]:
import pandas as pd
import numpy as np

In [2]:
food_q_matrix = np.load('food_matrices/q_matrix_new_6000.npy')
df = pd.DataFrame(data=food_q_matrix)

In [3]:
rows = []
for i in range(32):
    base_two_str = str(bin(i))[2:]
    zeros_to_append = 5 - len(base_two_str)
    for _ in range(zeros_to_append):
        base_two_str = '0' + base_two_str
    row_part = f'State {i}: |'
    #base_two_str = "".join(reversed(base_two_str))
    for binary in base_two_str:
        if binary == '0':
            row_part = row_part + ' ______ | '
        else: 
            row_part = row_part + ' GREEN | '
    rows.append(row_part)
cols = ["STRAIGHT", "LEFT", "RIGHT"]
df = pd.DataFrame(data=q_matrix, index=rows, columns=cols)
df.style.highlight_max(color = 'lightblue', axis = 1)

    0   1  2
0   0   0  0
1   2  39  0
2   0   0  0
3   2   0  0
4   0   0  1
.. ..  .. ..
59  0   0  0
60  0   0  0
61  0   0  0
62  0   0  0
63  0   0  0

[64 rows x 3 columns]