In [6]:
import numpy as np
import pandas as pd

In [51]:
q_matrix = np.load('matrices_kindofok/q_matrix_new_final.npy')

q_matrix[0][2] = 1
q_matrix[15][0] = 48
q_matrix[30][0] = 50
q_matrix[5][0] = 42 # Maybe remove?
q_matrix[31][0] = 57

q_matrix[11][1] = 41
q_matrix[11][2] = 51

q_matrix[4][0] = 64
q_matrix[4][1] = 39

q_matrix[23][0] = 43
q_matrix[24][1] = 37

In [52]:
rows = []
for i in range(32):
    base_two_str = str(bin(i))[2:]
    zeros_to_append = 5 - len(base_two_str)
    for _ in range(zeros_to_append):
        base_two_str = '0' + base_two_str
    row_part = f'State {i}: |'
    #base_two_str = "".join(reversed(base_two_str))
    for binary in base_two_str:
        if binary == '0':
            row_part = row_part + ' ______ | '
        else: 
            row_part = row_part + ' GREEN | '
    rows.append(row_part)
cols = ["STRAIGHT", "LEFT", "RIGHT"]
df = pd.DataFrame(data=q_matrix, index=rows, columns=cols)
df.style.highlight_max(color = 'lightblue', axis = 1)

In [22]:
df

                                                    STRAIGHT  LEFT  RIGHT
| ______ |  ______ |  ______ |  ______ |  _____...         0     0      0
| ______ |  ______ |  ______ |  ______ |  GREEN |        125   114     97
| ______ |  ______ |  ______ |  GREEN |  ______ |        126    91     96
| ______ |  ______ |  ______ |  GREEN |  GREEN |          94    92    120
| ______ |  ______ |  GREEN |  ______ |  ______ |         94    96    111
| ______ |  ______ |  GREEN |  ______ |  GREEN |           0    92     95
| ______ |  ______ |  GREEN |  GREEN |  ______ |          97    87     94
| ______ |  ______ |  GREEN |  GREEN |  GREEN |           95    93     91
| ______ |  GREEN |  ______ |  ______ |  ______ |         88    84     88
| ______ |  GREEN |  ______ |  ______ |  GREEN |          71    77      0
| ______ |  GREEN |  ______ |  GREEN |  ______ |         105    33     81
| ______ |  GREEN |  ______ |  GREEN |  GREEN |           76     0     85
| ______ |  GREEN |  GREEN |  ______ |  ______ |          93    93    109
| ______ |  GREEN |  GREEN |  ______ |  GREEN |           89    92     94
| ______ |  GREEN |  GREEN |  GREEN |  ______ |          130    93     83
| ______ |  GREEN |  GREEN |  GREEN |  GREEN |            95   118    106
| GREEN |  ______ |  ______ |  ______ |  ______ |         98   112     88
| GREEN |  ______ |  ______ |  ______ |  GREEN |          94    92     98
| GREEN |  ______ |  ______ |  GREEN |  ______ |          37    85     36
| GREEN |  ______ |  ______ |  GREEN |  GREEN |           93    82     94
| GREEN |  ______ |  GREEN |  ______ |  ______ |          64     0     73
| GREEN |  ______ |  GREEN |  ______ |  GREEN |            0     0      0
| GREEN |  ______ |  GREEN |  GREEN |  ______ |          118     0     93
| GREEN |  ______ |  GREEN |  GREEN |  GREEN |             0    74     82
| GREEN |  GREEN |  ______ |  ______ |  ______ |          94   117     91
| GREEN |  GREEN |  ______ |  ______ |  GREEN |           97    94     94
| GREEN |  GREEN |  ______ |  GREEN |  ______ |          117    39     77
| GREEN |  GREEN |  ______ |  GREEN |  GREEN |           167    93     93
| GREEN |  GREEN |  GREEN |  ______ |  ______ |           92    75     93
| GREEN |  GREEN |  GREEN |  ______ |  GREEN |            76   130      0
| GREEN |  GREEN |  GREEN |  GREEN |  ______ |           119    80     99
| GREEN |  GREEN |  GREEN |  GREEN |  GREEN |             74   120     75

In [11]:
for i in range(32):
    base_two_str = str(bin(i))[2:]
    zeros_to_append = 5 - len(base_two_str)
    for _ in range(zeros_to_append):
        base_two_str = '0' + base_two_str
    print(base_two_str)

00000
00001
00010
00011
00100
00101
00110
00111
01000
01001
01010
01011
01100
01101
01110
01111
10000
10001
10010
10011
10100
10101
10110
10111
11000
11001
11010
11011
11100
11101
11110
11111